### ISSUE TITLE
Add version conditions to all platform-specific modules

### ISSUE THREAD

**Issue by gecko0307** [SiegeLord/Tango-D2#21]
E. g. version(Posix), version(Windows), etc. 
Just for convenience, so that they won't be compiled even if someone imports them on incorrect platform.

**Comment by SiegeLord** [comment]
Thing is... if you import those modules, you in principle will use something from them that might be versioned out. Thus, you'll need a version statement inside your code too, no matter how the platform-specific modules are coded. At that point I think it's best to just force the version statements into the user's code so they are all in one place.

**Comment by gecko0307** [comment]
I understand. You see, for my projects I use my own incremental build tool, Cook (http://code.google.com/p/cook-build-automation-tool/). To deal with module dependency stuff, it has a simple import parser. It doesn't support version conditions, platform-specific modules are always imported, even I don't use anything from them. I got used to rely on compiler to version them out. I know, it's more about the tool itself than Tango, so maybe it's time to improve it...
