### ISSUE TITLE
fix bug for mac os x 10.7

### ISSUE THREAD

**Issue by oopos** [SiegeLord/Tango-D2#35]
diff --git a/tango/stdc/fenv.d b/tango/stdc/fenv.d
index c454131..e1f92ed 100644
--- a/tango/stdc/fenv.d
+++ b/tango/stdc/fenv.d
@@ -126,8 +126,8 @@ else version( linux )
 }
 else version( darwin )
 {
-    private extern fenv_t _FE_DFL_ENV;
-    fenv_t\* FE_DFL_ENV = &_FE_DFL_ENV;
-    private extern const fenv_t _FE_DFL_ENV;
-    const fenv_t\* FE_DFL_ENV = &_FE_DFL_ENV;
  }
  else version( freebsd )
  {
  @@ -136,7 +136,7 @@ else version( freebsd )
  }
  else version( solaris )
  {
-    private extern constfenv_t __fenv_dfl_env;
-    private extern const fenv_t __fenv_dfl_env;
   const fenv_t\* FE_DFL_ENV = &__fe_dfl_env;
  }
  else
  diff --git a/tango/stdc/posix/sys/select.d b/tango/stdc/posix/sys/select.d
  index d972bd3..ed46785 100644
  --- a/tango/stdc/posix/sys/select.d
  +++ b/tango/stdc/posix/sys/select.d
  @@ -133,7 +133,7 @@ else version( darwin )
  
  ```
   extern (D) int __FDELT( int d )
   {
  ```
-            return d / __NFDBITS;
- ```
         return d / cast(int)__NFDBITS;
   }
  
   extern (D) __fd_mask __FDMASK( int d )
  ```

**Comment by SiegeLord** [comment]
Fixed in 2e7ae05b6993837591900afd856226816c57d271. Thanks!
