### ISSUE TITLE
changes needed to build on win7-64, dmd2.058

### ISSUE THREAD

**Issue by jnorwood** [SiegeLord/Tango-D2#38]
G:\d\tango\Tango-D2>git diff
diff --git a/tango/stdc/fenv.d b/tango/stdc/fenv.d
index 92e54f1..998ac32 100644
--- a/tango/stdc/fenv.d
+++ b/tango/stdc/fenv.d
@@ -117,8 +117,8 @@ enum

 version( Win32 )
 {
-    private extern fenv_t _FE_DFL_ENV;
-    fenv_t\* FE_DFL_ENV = &_FE_DFL_ENV;
-    private extern const fenv_t _FE_DFL_ENV;
-    const fenv_t\* FE_DFL_ENV = &_FE_DFL_ENV;
  }
  else version( linux )
  {
  diff --git a/tango/sys/Process.d b/tango/sys/Process.d
  index f5705b0..a1aee2c 100644
  --- a/tango/sys/Process.d
  +++ b/tango/sys/Process.d
  @@ -1106,7 +1106,7 @@ class Process
  
  ```
       void append_arg(const(char)[] arg)
       {
  ```
-                         const(char)[] nextarg = a.substitute(`"`, `\"`);
-                         const(char)[] nextarg = arg.substitute(`"`, `\"`);
             //
             // find all instances where \" occurs, and double all the
             // backslashes.  Otherwise, it will fall under rule 1, and those

G:\d\tango\Tango-D2>

**Comment by SiegeLord** [comment]
Fixed in 50197db. Thanks!
