### ISSUE TITLE
errors compiling Tango2 with dmd 2.059 beta

### ISSUE THREAD

**Issue by jordisayol** [SiegeLord/Tango-D2#39]
tango/time/Time.d(487): Error: variable tango.time.Time.Time.epoch enum cannot be initialized with {0}

tango/sys/Process.d(527): Error: cannot implicitly convert expression (this._env) of type const(char[][const(char)[]]) to const(char[])[const(char)[]]

**Comment by SiegeLord** [comment]
I don't have the unstable DMD installed, so I don't know for sure if my fixes in 47b0d52937a45c1db631d8a4398eebb521c16701 worked. Thanks for reporting!

**Comment by jordisayol** [comment]
many thanks for your answer.
Now I got this error:
tango/time/Time.d(487): Error: variable tango.time.Time.Time.epoch enum cannot be initialized with {0L}

**Comment by SiegeLord** [comment]
Hmm. Could you please try this code and tell me if it gives the same error? This seems like a regression bug (I'll submit it if you confirm it).

``` d
struct A
{
    long a;
}

enum A a = {0};

void main() {}
```

**Comment by jordisayol** [comment]
no, this code compile and run without errors.

**Comment by jordisayol** [comment]
FYI there are 2 warnings and 1 error:

$ dmd -c -I. -m32 -release -ofobj/32/tango/io/FileScan.o tango/io/FileScan.d
tango.io.FileScan is deprecated. Please use tango.io.FilePath.toList or tango.io.vfs.\* instead.

$ dmd -c -I. -m32 -release -ofobj/32/tango/math/BigInt.o tango/math/BigInt.d
tango.math.BigInt is deprecated. Please use std.bigint instead.

$ dmd -c -I. -m32 -release -ofobj/32/tango/net/http/HttpClient.o tango/net/http/HttpClient.d
tango/time/Time.d(487): Error: variable tango.time.Time.Time.epoch enum cannot be initialized with {0L}

**Comment by SiegeLord** [comment]
I just tried the beta and the git version of DMD and I couldn't reproduce this error. I am not sure what is going on...

The warnings are okay.

**Comment by jordisayol** [comment]
Hmm. I've downloaded from git and compiled everything: dmd, phobos and druntime, and same result. there aren't orphans libs on the system.

$ ./build/bin/linux64/bob -vum=64 .
...
dmd -c -I. -m64 -release -oftango-net-http-HttpGet-release.o ./tango/net/http/HttpGet.d 
object.Exception@./build/src/bob.d(632): Process exited normally with return code 1
tango/time/Time.d(487): Error: variable tango.time.Time.Time.epoch enum cannot be initialized with {0L}

Same result with previous value:

$ ./build/bin/linux64/bob -vum=64 .
...
dmd -c -I. -m64 -release -oftango-net-http-HttpGet-release.o ./tango/net/http/HttpGet.d 
object.Exception@./build/src/bob.d(632): Process exited normally with return code 1
tango/time/Time.d(487): Error: variable tango.time.Time.Time.epoch enum cannot be initialized with {0}

**Comment by SiegeLord** [comment]
I submitted the DMD bug... hopefully it'll be fixed soon: http://d.puremagic.com/issues/show_bug.cgi?id=7823

**Comment by jordisayol** [comment]
This bug has been fixed. Now other errors raised with dmd v2.059 beta 2:

```
tango/text/Regex.d(1470): Error: no property 'any_char' for type 'CharClass!(dchar)'
tango/text/Regex.d(1550): Error: no property 'dot_oper' for type 'CharClass!(dchar)'
tango/text/Regex.d(1607): Error: no property 'alphanum_' for type 'CharClass!(dchar)'
tango/text/Regex.d(1610): Error: no property 'alphanum_' for type 'CharClass!(dchar)'
tango/text/Regex.d(1612): Error: function tango.text.Regex.TNFA!(dchar).TNFA.constructChars (dchar[] chars, const(Type) type) is not callable using argument types (_error_,Type)
tango/text/Regex.d(1612): Error: function tango.text.Regex.TNFA!(dchar).TNFA.constructChars (const(CharClass!(dchar)) charclass, const(Type) type) is not callable using argument types (_error_,Type)
tango/text/Regex.d(1707): Error: no property 'any_char' for type 'CharClass!(dchar)'
tango/text/Regex.d(2048): Error: no property 'any_char' for type 'CharClass!(dchar)'
```

**Comment by jordisayol** [comment]
same behavior with dmd 2.059 beta 3

**Comment by SiegeLord** [comment]
http://d.puremagic.com/issues/show_bug.cgi?id=7860

**Comment by jordisayol** [comment]
Fixed!
Now compiles without problems.

**Comment by SiegeLord** [comment]
Thanks for getting on my back and getting me to install the unstable dmd to produce those bug reports.
