### ISSUE TITLE
Tamgo-D2 deb packages

### ISSUE THREAD

**Issue by jordisayol** [SiegeLord/Tango-D2#40]
Tango-D2 deb packages available on:

https://code.google.com/p/d-apt/wiki/APT_Repository#APT_Repository_for_D

"d-apt" is an ATP repository to easily install/upgrade D binary packages on systems like Debian, Ubuntu, Linuxmint, etc.

Enjoy it!

**Comment by SiegeLord** [comment]
Great!

Just curious, what's inside the tango-doc package?

**Comment by jordisayol** [comment]
Download it ;-)
Seriously, libtango-doc, as all *-doc on d-apt, contains the library ddoc generated with the updated candydoc at https://github.com/eldar/candydoc and add a Linux menu entry for an easy use. It also contains the examples.
The icon is a very basic one, if you have a better one, please let me know.

**Comment by jordisayol** [comment]
BTW, If you like it, please don't hesitate to make advertising. Thanks!

**Comment by SiegeLord** [comment]
Mentioned in the readme: b3f47b95900b3b0db936424d53439a812a13641c

**Comment by jordisayol** [comment]
Thanks a lot! ;-)
