### ISSUE TITLE
ref required when struct declares opCmp

### ISSUE THREAD

**Issue by linkrope** [SiegeLord/Tango-D2#44]
In tango.time.Time, I had to change

```
    const int opCmp(const(TimeSpan) t)
```

and

```
    const int opCmp (const(Time) t)
```

into

```
    const int opCmp(ref const(TimeSpan) t)
```

and

```
    const int opCmp (ref const(Time) t)
```

(see http://dlang.org/operatoroverloading.html#compare)

Otherwise, for example tango.util.container.SortedMap with Time or TimeSpan keys does not work correctly.
The compareKey function calls TypeInfo_Struct.compare, and this function requires the ref for opCmp to be callled.

**Comment by SiegeLord** [comment]
Fixed in be20929fbd01dd1374f900345449f6190b84efb2 and bd6f82d615d0e72f4d482fe73d486a31e7231a97
