### ISSUE TITLE
xml is slow[er]

### ISSUE THREAD

**Issue by ariovistus** [SiegeLord/Tango-D2#45]
trying out the benchmark transformtango.d at 

https://bitbucket.org/ariovistus/xml-benchmarks/src/

with d1 tango and Tango-D2, I'm seeing Tango-D2 performing about 4 times slower with -O -inline -release

haven't played with it too much (e.g. turning off the gc), though.

**Comment by SiegeLord** [comment]
D1 profiling:

```
 33.84%  transformtango_  transformtango_d1  [.] _D5tango4text3xml10PullParser18__T10PullParserTaZ10PullParser4nextMFZE5tango4text3xml10Pul
  9.20%  transformtango_  transformtango_d1  [.] _D5tango4text3xml8Document15__T8DocumentTaZ8Document7Visitor7opApplyMFDFKPS5tango4text3xml
  6.48%  transformtango_  transformtango_d1  [.] _D5tango4text3xml10PullParser18__T10PullParserTaZ10PullParser15doAttributeNameMFZE5tango4t
  5.72%  transformtango_  transformtango_d1  [.] _D5tango4text3xml8Document14__T7XmlPathTaZ7XmlPath7NodeSet10descendantMFDFPS5tango4text3xm
  5.49%  transformtango_  transformtango_d1  [.] _D5tango4text3xml8Document14__T7XmlPathTaZ7XmlPath7NodeSet4testMFDFPS5tango4text3xml8Docum
```

D2 profiling:

```
 36.82%  transformtango  transformtango      [.] _D2gc3gcx3Gcx4markMFPvPviZv
 14.59%  transformtango  transformtango      [.] _D5tango4text3xml10PullParser18__T10PullParserTaZ10PullParser4nextMFNdZE5tango4text3xml10P
  8.59%  transformtango  transformtango      [.] _D2gc3gcx3Gcx8findPoolMFPvZPS2gc3gcx4Pool
```

So yeah, some accidentally introduced GC activity. I'll look into it.

**Comment by SiegeLord** [comment]
Can you see if 44295fade89e638e664ca8371fa62615a03e37f2 fixes this? It seems to do so in my case for the most part.

**Comment by ariovistus** [comment]
with 44295fa, I'm seeing 
d1: cycle complete in average of 17.40 ms
d2: cycle complete in average of 19.51 ms

so yep, that took care of most of it.

The fix is rather interesting. I imagine the reason for it would be enum copies out the literal wherever the symbol is used, but const just has one copy.

Now I'm going to have to go look in my code and see if I've done something similar.

Nice work!

**Comment by SiegeLord** [comment]
Removed all enum arrays: d359cf3c831f696af4578b6a048111f58302721d

Bug submitted to DMD: http://d.puremagic.com/issues/show_bug.cgi?id=8903

I think this matter is essentially closed... the remaining performance difference is probably noise.
