### ISSUE TITLE
errors compiling with dmd 2.061 (alpha)

### ISSUE THREAD

**Issue by jordisayol** [SiegeLord/Tango-D2#46]
```
tango/sys/SharedLib.d(251): Error: Cannot modify 'this'
tango/core/BitArray.d(867): Error: function tango.core.BitArray.BitArray.opAssign (bool[] bits) is not callable using argument types (BitArray)
tango/core/BitArray.d(867): Error: cannot implicitly convert expression (this.dup()) of type BitArray to bool[]
tango/core/BitArray.d(892): Error: function tango.core.BitArray.BitArray.opAssign (bool[] bits) is not callable using argument types (BitArray)
tango/core/BitArray.d(892): Error: cannot implicitly convert expression (this.dup()) of type BitArray to bool[]
```

**Comment by SiegeLord** [comment]
Those look like regressions with dmd. I submitted the issues, and will wait until they are addressed before looking into changing this code.

http://d.puremagic.com/issues/show_bug.cgi?id=9077
http://d.puremagic.com/issues/show_bug.cgi?id=9079

**Comment by jordisayol** [comment]
I got these errors compiling with last dmd 2.061 beta on Linux:

```
$ dmd -c -O -release -m64 -ofobj/64/tango/time/Clock.o tango/time/Clock.d
tango/time/Clock.d(292): Error: TimeSpan(0L) is not an lvalue

$ dmd -c -O -release -m64 -ofobj/64/tango/time/chrono/Gregorian.o tango/time/chrono/Gregorian.d
tango/time/Time.d(487): Error: Time(0L) is not an lvalue
```

I got these warnings too:

```
$ dmd -c -O -release -m64 -ofobj/64/tango/io/FileScan.o tango/io/FileScan.d
tango.io.FileScan is deprecated. Please use tango.io.FilePath.toList or tango.io.vfs.* instead.

$ dmd -c -O -release -m64 -ofobj/64/tango/math/BigInt.o tango/math/BigInt.d
tango.math.BigInt is deprecated. Please use std.bigint instead.

$ dmd -o- doc/candydoc/modules.ddoc doc/candydoc/candy.ddoc -Dfdoc/tango_text_xml_DocEntity.html tango/text/xml/DocEntity.d
(4): Error: unterminated string constant starting at (2)
```

**Comment by SiegeLord** [comment]
The errors are a DMD regression: http://d.puremagic.com/issues/show_bug.cgi?id=9218

The first two warnings are meant to be there. The third I'll fix in a bit.

**Comment by jordisayol** [comment]
dmd v2.061 final release still raise these errors. If there is not a way to override them, Tango will be not usable till the next dmd release

**Comment by SiegeLord** [comment]
I fixed most of the issues as of https://github.com/SiegeLord/Tango-D2/commit/54f56eeb74fecc158e72aef5fce00107a0e070e1 . Note that JSON stuff isn't working quite right due to bug http://d.puremagic.com/issues/show_bug.cgi?id=9259.

**Comment by jordisayol** [comment]
At least everything compiles now. Many many thanks!

BTW Happy new year.
