### ISSUE TITLE
Strange error using tango.util.compress.Zip

### ISSUE THREAD

**Issue by jacob-carlborg** [SiegeLord/Tango-D2#48]
When I run the following example I get files with strange names all over the working directory. Names like `!%AF`, `??` and similar. On 64bit I get one file. On 32bit I get around 20 files.

``` d
import tango.util.compress.Zip;

void main ()
{
    auto src = "path/to.zip";
    auto dest = "tmp";

    extractArchive(src, dest);
}
```

I'm using Mac OS X.

**Comment by SiegeLord** [comment]
What compiler/version are you using?

I just tested it with DMD 2.061 32, 64 bit and LDC2 2.060 64 bit. The DMD compilers worked fine, but LDC2 produced yet another error (object.Exception@tango/util/compress/Zip.d(1884): unexpected end of stream). Something is definitely fishy here.

**Comment by jacob-carlborg** [comment]
DMD 2.061.

**Comment by jacob-carlborg** [comment]
The one file it outputs when compiling for 64bit has the correct content but not the correct filename.

**Comment by jacob-carlborg** [comment]
I just did a bisect of Tango using DMD 2.057. All versions worked correctly. It looks like this is an issue with DMD. Next step is to try each version up to DMD 2.061.

**Comment by jacob-carlborg** [comment]
I tried with DMD 2.061, it works if I compile Tango without any special flags. If I compile with `-O -release -inline` it fails. So I guess it's some issue with the optimizer.

**Comment by jacob-carlborg** [comment]
I've managed to get a small test case. It seems to be a problem with the inliner in DMD: http://d.puremagic.com/issues/show_bug.cgi?id=9356

Do you want to keep this issue open or should I close it?

**Comment by SiegeLord** [comment]
Wow, thanks! Sorry I didn't help much with this... just been too busy with work...

I'll close this as this isn't necessarily a bug with Tango's code... additionally, the standard build instructions don't pass -inline as far as I can tell, so no workarounds are needed.

I probably should keep a list of D compiler bugs that affect Tango.
