### ISSUE TITLE
errors compiling with dmd 2.063.2 (windows)

### ISSUE THREAD

**Issue by Domain** [SiegeLord/Tango-D2#52]
object.Exception@.\build\src\bob.d(632): Process exited normally with return code 1
.\tango\core\tools\WinStackTrace.d(423): Error: argument uint[][0u] to typeof is not an expression
.\tango\core\tools\WinStackTrace.d(423): Error: argument uint[][0u] to typeof is not an expression
.\tango\core\tools\WinStackTrace.d(198): Error: template instance tango.core.tools.WinStackTrace.alloc!(uint[], const(int)) error instantiating
.\tango\core\tools\WinStackTrace.d(519): Error: argument AddrDebugInfo[][0u] to typeof is not an expression
.\tango\core\tools\WinStackTrace.d(519): Error: argument AddrDebugInfo[][0u] to typeof is not an expression
.\tango\core\tools\WinStackTrace.d(976): Error: template instance tango.core.tools.WinStackTrace.append!(AddrDebugInfo[], AddrDebugInfo) error instantiating
.\tango\core\tools\WinStackTrace.d(423): Error: argument char[][0u] to typeof is not an expression
.\tango\core\tools\WinStackTrace.d(423): Error: argument char[][0u] to typeof is not an expression
.\tango\core\tools\WinStackTrace.d(987): Error: template instance tango.core.tools.WinStackTrace.alloc!(char[], uint) error instantiating
.\tango\core\tools\WinStackTrace.d(519): Error: argument char_[][0u] to typeof is not an expression
.\tango\core\tools\WinStackTrace.d(519): Error: argument char_[][0u] to typeof is not an expression
.\tango\core\tools\WinStackTrace.d(990): Error: template instance tango.core.tools.WinStackTrace.append!(char_[], char_) error instantiating

**Comment by SiegeLord** [comment]
Should be fixed by 01b1babc411d1a128c84d68d9720eb516dfa16e0.

Thanks.
