### ISSUE TITLE
building example with gdc

### ISSUE THREAD

**Issue by albatr0z** [SiegeLord/Tango-D2#53]
Hi, I've seen that GDC is not really supported, but maybe you have some clue on how to solve this issue, since TANGO is built with GDC but issue is using the library from any module.
I have a module that only imports tango.io.Stdout. When built with DMD there are no problems, with GDC I get the following error:

<pre>
$ gdc -I/usr/local/include/d -I/opt/gdc/include/d/4.8.1 newmain.d -ot.o -ltango-gdc
/usr/local/lib/libtango-gdc.a(Buffered.o):(.data+0xc4): undefined reference to `_DT36_D5tango2io6device7Conduit12OutputFilter7conduitMFNdZC5tango2io5model8IConduit8IConduit'
/usr/local/lib/libtango-gdc.a(Buffered.o):(.data+0xcc): undefined reference to `_DT36_D5tango2io6device7Conduit12OutputFilter5closeMFZv'
/usr/local/lib/libtango-gdc.a(Buffered.o):(.data+0xd8): undefined reference to `_DT36_D5tango2io6device7Conduit12OutputFilter6outputMFNdZC5tango2io5model8IConduit12OutputStream'
/usr/local/lib/libtango-gdc.a(Buffered.o):(.data+0x184): undefined reference to `_DT36_D5tango2io6device7Conduit11InputFilter7conduitMFNdZC5tango2io5model8IConduit8IConduit'
/usr/local/lib/libtango-gdc.a(Buffered.o):(.data+0x18c): undefined reference to `_DT36_D5tango2io6device7Conduit11InputFilter5closeMFZv'
/usr/local/lib/libtango-gdc.a(Buffered.o):(.data+0x198): undefined reference to `_DT36_D5tango2io6device7Conduit11InputFilter5inputMFNdZC5tango2io5model8IConduit11InputStream'
collect2: error: ld returned 1 exit status
</pre>

gdc is at the latest version on github. commit d2a4df411a81573c621cfb878e201223ab6c3d62

Thanks

**Comment by SiegeLord** [comment]
I've never managed to build GDC, hence the lack of support. I shall make another attempt and see if I will be able to help.

**Comment by albatr0z** [comment]
I've just tested with gdc-4.8 provided on Debian, I did not build Tango this time, just used the one built with gdc from git version.
The error is the same. 
Thanks for your time and support.

**Comment by albatr0z** [comment]
Just found the GDC bugzilla and there is a open ticket for an issue that may be related:
http://bugzilla.gdcproject.org/show_bug.cgi?id=27

Will close the issue, this is related to gdc not Tango.
