### ISSUE TITLE
building tango rev ff2b1d3

### ISSUE THREAD

**Issue by bioinfornatics** [SiegeLord/Tango-D2#56]
Dear i fail to build tango  rev ff2b1d3 with ldc .

Build log:
- http://kojipkgs.fedoraproject.org//work/tasks/6601/6116601/build.log

**Comment by SiegeLord** [comment]
https://github.com/ldc-developers/ldc/issues/535

**Comment by SiegeLord** [comment]
Should work fine now with the latest LDC.
