### ISSUE TITLE
Error running when compiling on Debian 64-bit with dmd v2.064.2

### ISSUE THREAD

**Issue by jordisayol** [SiegeLord/Tango-D2#58]
A simple:

```
import tango.io.Stdout;

void main()
{
    Stdout("hello tango!").newline;
}
```

If compiled against tango shared library, I got this error when running:

```
$ ./test
object.Exception@tango/net/util/c/OpenSSL.d(1012): Could not load OpenSSL library.
----------------
Segmentation fault encountered at:
Segmentation fault
```

It properly runs when compiled with dmd v2.063.2

**Comment by jordisayol** [comment]
Executable needs linking name "libssl.so" instead soname/real lib name "libssl.so.1.0.0" at runtime.

On Debian, to run Tango programs, "libssl-dev" development package has to be installed. This has no sense.

**Comment by SiegeLord** [comment]
This is an unfortunate consequence of how the API works today. The OpenSSL library is loaded when the `static this` runs, which is always when you're using the shared library (with a static library it only runs if you're using the OpenSSL modules). It is unfortunate that this works this way, so the best I can do is to make it look for the right library at least.

**Comment by jordisayol** [comment]
Thank you!
