### ISSUE TITLE
Unexpected redirect for method GET

### ISSUE THREAD

**Issue by jacob-carlborg** [SiegeLord/Tango-D2#71]
When using `HttpGet` to fetch a resource which is redirected I get the above exception. The reason is that `is` is used to compare manifest constants [1]. This comparison will always be false when using `HttpGet`. That's because with manifest consonants the usage is replaced with the actual values, resulting in two different strings (in memory) [2].

[1] https://github.com/SiegeLord/Tango-D2/blob/d2port/tango/net/http/HttpClient.d#L577
[2] https://github.com/SiegeLord/Tango-D2/blob/d2port/tango/net/http/HttpGet.d#L61

**Comment by SiegeLord** [comment]
Hopefully fixed by bb051f2c58512f10829397cf35e549cc046bd78f.
