### ISSUE TITLE
errors 2.067

### ISSUE THREAD

**Issue by jaffa4** [SiegeLord/Tango-D2#83]
Building tango 1.0.1+2.067 configuration "static", build type debug.
Running dmd...
tango.io.FileScan is deprecated. Please use tango.io.FilePath.toList or tango.io.vfs.\* instead.
tango.math.BigInt is deprecated. Please use std.bigint instead.
not yet available for windows
tango\io\selector\SelectSelector.d(156): Error: cannot modify struct this._readSet HandleSet with immutable members
tango\io\selector\SelectSelector.d(157): Error: cannot modify struct this._writeSet HandleSet with immutable members
tango\io\selector\SelectSelector.d(158): Error: cannot modify struct this._exceptionSet HandleSet with immutable members
tango\io\selector\SelectSelector.d(159): Error: cannot modify struct this._selectedReadSet HandleSet with immutable members
tango\io\selector\SelectSelector.d(160): Error: cannot modify struct this._selectedWriteSet HandleSet with immutable members
tango\io\selector\SelectSelector.d(161): Error: cannot modify struct this._selectedExceptionSet HandleSet with immutable members
tango\math\IEEE.d(858): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<='
tango\stdc\math.d(436): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!>'
tango\stdc\math.d(437): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!>'
tango\stdc\math.d(438): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!>'
tango\stdc\math.d(441): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!>='
tango\stdc\math.d(442): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!>='
tango\stdc\math.d(443): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!>='
tango\stdc\math.d(446): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<'
tango\stdc\math.d(447): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<'
tango\stdc\math.d(448): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<'
tango\stdc\math.d(451): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<='
tango\stdc\math.d(452): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<='
tango\stdc\math.d(453): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<='
tango\stdc\math.d(456): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<>'
tango\stdc\math.d(457): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<>'
tango\stdc\math.d(458): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<>'
FAIL .dub\build\static-debug-windows-x86-dmd_2067-9C02248FA20BAB6DD8CA236C26D31263\ tango staticLibrary
Error executing command run:
dmd failed with exit code 1.

**Comment by SiegeLord** [comment]
Should be fixed now.
