### ISSUE TITLE
Unable 

### ISSUE THREAD

**Issue by jelly** [SiegeLord/Tango-D2#87]
I've tried to compile the master with 3.7 but it gives me the following compile error.

`dmd -O -m64 -L-ldl -m64  -c tango/math/Probability.d -ofobjs/tango/math/Probability.o
tango/math/IEEE.d(858): Deprecation: use std.math.isNaN to deal with NaN operands rather than floating point operator '!<='
dmd -O -m64 -L-ldl -m64  -c tango/math/random/ExpSource.d -ofobjs/tango/math/random/ExpSource.o
dmd -O -m64 -L-ldl -m64  -c tango/math/random/Kiss.d -ofobjs/tango/math/random/Kiss.o
dmd -O -m64 -L-ldl -m64  -c tango/math/random/NormalSource.d -ofobjs/tango/math/random/NormalSource.o
tango.math.BigInt is deprecated. Please use std.bigint instead.
tango/io/vfs/ZipFolder.d(302): Error: function tango.io.vfs.ZipFolder.ZipSubFolder.toString cannot have an in contract when overriden function object.Object.toString does not have an in contract
tango/io/vfs/ZipFolder.d(977): Error: function tango.io.vfs.ZipFolder.ZipFile.toString cannot have an in contract when overriden function object.Object.toString does not have an in contract
dmd -O -m64 -L-ldl -m64  -c tango/math/random/Random.d -ofobjs/tango/math/random/Random.o
dmd -O -m64 -L-ldl -m64  -c tango/math/random/Twister.d -ofobjs/tango/math/random/Twister.o
dmd -O -m64 -L-ldl -m64  -c tango/math/random/Ziggurat.d -ofobjs/tango/math/random/Ziggurat.o
build/Makefile:131: recipe for target 'objs/tango/io/vfs/ZipFolder.o' failed
make: *** [objs/tango/io/vfs/ZipFolder.o] Error 1
make: *** Waiting for unfinished jobs....
==> ERROR: A failure occurred in build().`

**Comment by SiegeLord** [comment]
Should be fixed now.
