### ISSUE TITLE
compiler with ldc 1.12 is error

### ISSUE THREAD

**Issue by huangyy** [SiegeLord/Tango-D2#97]
error info is :
hyy@hyy-Dell:~/dev/dlang/tango$ dub build --build=release --arch=x86_64 --compiler=ldc
Fetching tango 1.0.4+2.0.83 (getting selected version)...
Performing "release" build using ldc for x86_64.
tango 1.0.4+2.0.83: building configuration "static"...
../../../.dub/packages/tango-1.0.4_2.0.83/tango/tango/core/Vararg.d(43,19): Error: module `vararg` is in file 'ldc/vararg.d' which cannot be read
import path[0] = ../../../.dub/packages/tango-1.0.4_2.0.83/tango
import path[1] = /usr/local/ldc2-1.12.0-linux-x86_64/bin/../import/ldc
import path[2] = /usr/local/ldc2-1.12.0-linux-x86_64/bin/../import
ldc failed with exit code 1.

**Comment by SiegeLord** [comment]
Should be fixed by #100.
